services:
  backend:
    build: ./backend # Path to backend Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development

  frontend:
    build: ./frontend # Path to frontend Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
